name: Publish compiled jar to GitHub releases
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: Build jar
        run: mvn --batch-mode --update-snapshots verify
      - name: Move generated jar file
        run: mv target/ingame-*.jar ingame.jar
      - name: Create Release
        id: create_release
        if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/master')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ingame-${{github.sha}}
          release_name: Release ${{github.sha}}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/master')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./ingame.jar
          asset_name: ingame.jar
          asset_content_type: application/java-archive
      - name: trigger docker image building
        run: |
            curl -H "Authorization: token "${{ secrets.PERSONAL_ACCESS_TOKEN }}"" \
              --request POST \
              --data '{"event_type": "build"}' \
              https://api.github.com/repos/bolt-rip/config-pgm/dispatches
